# Generated by Django 2.1.5 on 2019-02-05 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='emailid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeruser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
